name: Lint

on:
  workflow_call:
    inputs:
      node-version:
        type: string
        default: "22"
      cache-key:
        type: string
        required: true
      store-path:
        type: string
        required: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/action-setup@v6
        with:
          version: 9
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ inputs.node-version }}
      - uses: actions/cache@v6
        with:
          path: ${{ inputs.store-path }}
          key: ${{ inputs.cache-key }}
      - run: pnpm install --frozen-lockfile
      - run: pnpm lint
